# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MobilityAreas
                                 A QGIS plugin
 This plugin build dynamic mobility areas based on origin destination data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-05
        copyright            : (C) 2021 by Patrick Palmier/Cerema Hauts-de-France
        email                : patrick.palmier@cerema.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Patrick Palmier/Cerema Hauts-de-France'
__date__ = '2021-08-05'
__copyright__ = '(C) 2021 by Patrick Palmier/Cerema Hauts-de-France'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MobilityAreas class from file MobilityAreas.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MobilityAreas import MobilityAreasPlugin
    return MobilityAreasPlugin()
